export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const INCREMENT_COUNTER_IMMERJS = "INCREMENT_COUNTER_IMMERJS";
export const DECREMENT_COUNTER_IMMERJS = "DECREMENT_COUNTER_IMMERJS";
